---
- name: Add Docker repository for Debian distros
  include_tasks: "repo-debian-like.yaml"
  when: is_debian_like

- name: Install Docker for Debian distros
  include_tasks: "docker-debian-like.yaml"
  when: is_debian_like

- name: Make sure docker is running
  systemd:
    state: started
    name: docker
    enabled: yes
  when: is_debian_like
