---
- name: Install runtime
  include_tasks: docker.yaml"

- name: Uninstall docker
  include_tasks: uninstall-docker.yaml
  when: agorakube_base_components.container.engine == "docker"
  tags: [ 'never', 'uninstall' ]
