---
- hosts: client2
  become: true
  tasks:
  - name: Vérification de la connexion
    ping:
  - name: installation package serveur MySQL [mysql-server]
    apt:
      name: mysql-server
      state: latest
      update_cache: yes
  - name: Installation package python-mysqldb
    apt:
      name: python-mysqldb
      state: latest
  - name: Autorisation connexions à distance
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp:   '^bind-address'
      line: 'bind-address = 0.0.0.0'
    notify:
      - Relancement du service mysql
  - name: Gestion du service mysql
    service:
      name: mysql
      state: started
      enabled: yes
  - name: Création de l utilisateur boby
    no_log: true
    mysql_user:
      name: boby
      host: 10.10.20.4
      password: azerty
      state: present
      priv: '*.*:ALL'
  handlers:
  - name: Relancement du service mysql
    service:
      name: mysql
      state: restarted

- hosts: client1
  become: true
  tasks:
  - name: Vérification de la connexion
    ping:
  - name: Installation client MySQL [mysql-client]
    apt:
      name: mysql-client
      state: latest