---
- name: Add Docker repository for Debian lagorakube distros
  include_tasks: "repo-debian-like.yaml"

#- name: Install package Iptables
#  package:
#    name: iptables
#    state: latest

#- name: Ensure Iptable mode selected is Legacy
#  alternatives:
#    name: iptables
#    path: /usr/sbin/iptables-legacy
#  when: ansible_distribution|lower == 'debian'

- name: Install Docker for Debian lagorakube distros
  include_tasks: "docker-debian-like.yaml"

#- name: Make sure /etc/docker exist
#  file:
#    path: /etc/docker
#    state: directory

#- name: Configure /etc/docker/daemon.json
#  copy:
#    dest: /etc/docker/daemon.json
#    src: daemon.json
#  notify:
#    - Reload docker

- name: Make sure docker is running
  systemd:
    state: started
    name: docker
    enabled: yes
