---
- hosts: client2
  become: true
  vars:
    mysql_bind_address: 10.10.20.5
    mysql_users:
      pepito:
        priv: '*.*:ALL'
        host: '10.10.20.4'
        password: 'azerty'

  tasks:
  - name: Vérification de la connexion
    ping:
  - name: installation package serveur MySQL [mysql-server]
    apt:
      name: mysql-server
      state: latest
      update_cache: yes
  - name: Installation package python-mysqldb
    apt:
      name: python-mysqldb
      state: latest
  - name: Autorisation connexions à distance
    lineinfile:
      path: /etc/mysql/mysql.conf.d/mysqld.cnf
      regexp:   '^bind-address'
      line: "bind-address = {{ mysql_bind_address }}"
    notify:
      - Relancement du service mysql
  - name: Gestion du service mysql
    service:
      name: mysql
      state: started
      enabled: yes
  - name: Création de l utilisateur MySQL
    mysql_user:
      state: present
      name: "{{ item.key }}"
      host: "{{ item.value.host }}"
      password: "{{ item.value.password }}"
      priv: "{{ item.value.priv }}"
    loop: "{{ query('dict', mysql_users) }}"

  handlers:
  - name: Relancement du service mysql
    service:
      name: mysql
      state: restarted

